# Generated by Django 4.2.3 on 2023-08-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
    ]
